[package]
name = "axipi"
version.workspace = true
edition.workspace = true
authors = ["Keyang Hu <keyang.hu@qq.com>"]
description = "ArceOS IPI management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axipi"
documentation = "https://arceos-org.github.io/arceos/axipi/index.html"

[features]
default = []
smp = []
preempt = []

[dependencies]
axconfig.workspace = true
axhal = { workspace = true, features = ["ipi"] }
kspin.workspace = true
lazyinit.workspace = true
log.workspace = true
percpu.workspace = true
crate_interface = "0.1.4"
axcpu = { git = "https://github.com/arceos-org/axcpu.git", tag = "dev-v03" }
axtask = { workspace = true, features = ["task-ext"] }
page_table_multiarch.workspace = true